# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jfrances <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/10 02:41:43 by jfrances          #+#    #+#              #
#    Updated: 2019/11/10 03:22:23 by jfrances         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILE = rush-2
SRC = ./src/
HEAD = ./headers/
SRC_GRAB = $(SRC)main.c $(SRC)concheck.c 
COMPILE = -Wall -Werror -Wextra
MISC = .swp

gcc $(COMPILE) $(SRC) 

all:

clean:
		/bin/rm -f $(MISC)
fclean: clean 

